/* Document bytes. Two drivers behind one interface so the deployment can start
 * on a Railway volume and move to a bucket without touching callers.
 *
 * Bytes are encrypted before they arrive here and decrypted after they leave,
 * so neither driver ever sees plaintext. */
import fs from "node:fs/promises";
import path from "node:path";
import config from "../config.js";

const local = {
  async put(key, bytes) {
    const full = resolveLocal(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, bytes, { mode: 0o600 });
  },
  async get(key) {
    return fs.readFile(resolveLocal(key));
  },
  async del(key) {
    await fs.rm(resolveLocal(key), { force: true });
  },
  async check() {
    await fs.mkdir(config.storage.localDir, { recursive: true });
    const probe = path.join(config.storage.localDir, ".writable");
    await fs.writeFile(probe, "ok");
    await fs.rm(probe, { force: true });
  },
};

/* Keys are generated by us, never derived from a filename. This still refuses
   anything that could climb out of the directory, because the cost of being
   wrong here is reading arbitrary files off the disk. */
function resolveLocal(key) {
  if (!/^[A-Za-z0-9/_-]+\.bin$/.test(key) || key.includes("..")) {
    throw new Error("invalid storage key");
  }
  const root = path.resolve(config.storage.localDir);
  const full = path.resolve(root, key);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error("storage key escapes root");
  }
  return full;
}

/* The S3 client is loaded only if the driver is selected, so a local/volume
   deployment never installs or ships it. */
let s3client = null;
async function s3() {
  if (s3client) return s3client;
  let mod;
  try {
    mod = await import("@aws-sdk/client-s3");
  } catch {
    throw new Error(
      "STORAGE_DRIVER=s3 requires @aws-sdk/client-s3. Run: npm install @aws-sdk/client-s3"
    );
  }
  const { S3Client } = mod;
  s3client = {
    mod,
    client: new S3Client({
      region: config.storage.s3.region,
      endpoint: config.storage.s3.endpoint,
      forcePathStyle: true,
      credentials: {
        accessKeyId: config.storage.s3.accessKeyId,
        secretAccessKey: config.storage.s3.secretAccessKey,
      },
    }),
  };
  return s3client;
}

const s3driver = {
  async put(key, bytes) {
    const { mod, client } = await s3();
    await client.send(new mod.PutObjectCommand({
      Bucket: config.storage.s3.bucket, Key: key, Body: bytes,
    }));
  },
  async get(key) {
    const { mod, client } = await s3();
    const res = await client.send(new mod.GetObjectCommand({
      Bucket: config.storage.s3.bucket, Key: key,
    }));
    const chunks = [];
    for await (const chunk of res.Body) chunks.push(chunk);
    return Buffer.concat(chunks);
  },
  async del(key) {
    const { mod, client } = await s3();
    await client.send(new mod.DeleteObjectCommand({
      Bucket: config.storage.s3.bucket, Key: key,
    }));
  },
  async check() {
    if (!config.storage.s3.bucket) throw new Error("S3_BUCKET is not set");
    await s3();
  },
};

export const storage = config.storage.driver === "s3" ? s3driver : local;

export function newStorageKey(documentId) {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `${yyyy}/${mm}/${documentId}.bin`;
}
